import { ToastContainer } from "react-toastify";
import type { Metadata } from "next";
import "./globals.css";
import ProfileProvider from "./provider";
import QueryProvider from "./QueryProvider";

// ? metadata ini untuk title browser, sifatnya macam z-index, layout defaultnya, ada yg static dan ada yg dinamis
export const metadata: Metadata = {
  title: {
    default: "Next Prototype",
    template: "%s | Next Prototype",
  },
  description: "Generated by Me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ToastContainer />
        <QueryProvider>
          <ProfileProvider>{children}</ProfileProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

// ? Root Layout adalah “entry point” untuk seluruh aplikasi

// ? Di Next.js 13+, app/layout.tsx itu layout root, yang merangkum seluruh aplikasi.

// ? Jadi setiap kali URL berubah, root layout di-render ulang dari awal untuk melakukan SSR dan hydrate client.
